version: "3.7"

services:
  mllp-catcher:
    image: rivethealth/mllp-http
    container_name: mllp-catcher
    command: "mllp2http -p 2595 http://http-debugger:3000"
    ports:
      - "2595:2595"

  http-debugger:
    image: czerasz/http-debugger
    container_name: http-debugger
    ports:
      - "3000:3000"
